### ISSUE TITLE
Add Citation.cff File Support in Release Job API

### ISSUE THREAD

**Issue by hollowaykeanho** [ChewKeanHo/AutomataCI#142]
### Description

Full formats generated from [source](https://citation-file-format.github.io/cff-initializer-javascript). Integration into the system would be good.

```
# This CITATION.cff file was generated with cffinit.
# Visit https://citation-file-format.github.io/cff-initializer-javascript to generate yours today!

cff-version: 1.2.0
title: Sample Software
message: >-
  If you're using this software, please proceed to cite us
  using the following formats
type: software
authors:
  - given-names: Mary
    family-names: Lincoln
    name-suffix: M
    email: mary.lincon@gmail.com
    affiliation: Independent
    orcid: 'https://orcid.org/0000-0000-0000-0000'
  - given-names: Jane
    family-names: Smith
    name-suffix: Mike
    email: jane.smith@gmail.com
    affiliation: Independent
    orcid: 'https://orcid.org/0000-0000-0000-1111'
identifiers:
  - type: doi
    value: 10.5281/zenodo.123456
    description: Paper
repository-code: 'https://github.com/citation-file-format'
url: 'https://www.example.com/'
repository: 'https://other.repo/'
repository-artifact: 'https://artifact.repo/'
abstract: >-
  The development of AI has reached a level of
  sophistication where it can generate new content based on
  internalized datasets, including both text and images,
  across different AI products. As of 2023, AI assistant is
  being used for testing and path-finding purposes and has
  garnered significant attention from various industries
  worldwide. At ZORALab, the author tested and deployed
  several AI assistant products, including Chat GPT-3 and
  DALL·E 2 from OpenAI and StableDiffusion from Stability
  AI, specifically for commercial use. The work covered in
  this paper includes successful context and content
  reviews, as well as the creation of logo vector graphics
  using these AI assisting tools. This case study
  demonstrates the potential for AI for improving commercial
  work processes. This paper provides a summarized review of
  applied AI products offered by OpenAI and Stability AI
  covering their purpose, roles, capabilities, and outputs.
  The author then identifies commercial requirements at
  ZORALab that are applicable for deployment, outlines the
  reasoning behind these decisions, and assesses the risks
  associated with implementation. A work process is
  developed as a result of this analysis. The paper
  concludes with the author's analytic findings highlighting
  the potential for AI to improve commercial work processes
  and outcomes.


  WARNING: Paper contains censored explicit images generated
  by AI, intentionally and unintentionally due to testing.
  Viewer is advised.
keywords:
  - keyword1
  - keyword2
  - keyword3
license: AFL-1.1
commit: 1ff847d81f29c45a3a1a5ce73d38e45c2f319bba
version: v1.0.0
date-released: '2023-12-31'
```

### Expected Behavior

`CITATION.cff` is generated and regenerated in the Release CI Job.

### Current Behavior

`CITATION.cff` is not supported.

### Associated Data Files

1. https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files#citation-formats
2. https://github.com/citation-file-format/ruby-cff
3. https://github.com/citation-file-format/citation-file-format/tree/main
4. https://citation-file-format.github.io/

**Comment by hollowaykeanho** [comment]
Translate for AutomataCI generator:

```
# This CITATION.cff file was generated with cffinit.
# Visit https://citation-file-format.github.io/cff-initializer-javascript to generate yours today!

cff-version: 1.2.0
message: >-
  If you're using this software, please proceed to cite us
  using the following formats
type: software
authors:
  - given-names: Mary
    family-names: Lincoln
    name-suffix: M
    email: mary.lincon@gmail.com
    affiliation: Independent
    orcid: 'https://orcid.org/0000-0000-0000-0000'
  - given-names: Jane
    family-names: Smith
    name-suffix: Mike
    email: jane.smith@gmail.com
    affiliation: Independent
    orcid: 'https://orcid.org/0000-0000-0000-1111'
identifiers:
  - type: doi
    value: 10.5281/zenodo.123456
    description: Paper
keywords:
  - keyword1
  - keyword2
  - keyword3
repository-code: '${PROJECT_REPO}'
url: '${PROJECT_CONTACT_WEBSITE}'
repository: '${PROJECT_STATIC_REPO}'
repository-artifact: '${PROJECT_STATIC_URL}'
license: ${PROJECT_LICENSE}
version: ${PROJECT_VERSION}
title: ${PROJECT_NAME} ($PROJECT_VERSION})
abstract: >-
  {{ Generated by Processing Abstract file }}
date-released: '{{ Generated by Processing Release date }}'
```
